name: Build

on:
    push:
        branches:
            - main
        paths-ignore:
            - 'docs/examples/**'
            - 'README.md'
    pull_request:
        types: [opened, synchronize, reopened]
jobs:
    build:
        name: Build and analyze
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                java-version: 21
                distribution: 'temurin'
                cache: gradle

            - name: Build and analyze
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              run: ./gradlew build sonar --info
